### ISSUE TITLE
mlat-client won't install due to wrong Python version

### ISSUE THREAD

**Issue by timtuxworth** [abcd567a/mlat-client-package#2]
When I try to install this mlat-client on my 32 bit Buster Raspberry pi I get this:

`pi@raspberrypi:~ $ sudo dpkg -i mlat-client_*.deb
(Reading database ... 100432 files and directories currently installed.)
Preparing to unpack mlat-client_0.2.11_BUSTER_armhf.deb ...
Unpacking mlat-client (0.2.11) over (0.2.11) ...
dpkg: dependency problems prevent configuration of mlat-client:
 mlat-client depends on python3 (<< 3.8); however:
  Version of python3 on system is 3.9.2-3.
 mlat-client depends on python3.7:any.

dpkg: error processing package mlat-client (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mlat-client
`

**Comment by abcd567a** [comment]
(1) `Unpacking mlat-client (0.2.11) over (0.2.11) ...`
Above output from your installation shows that you already had mlat-client (0.2.11) installed, and tried to install it again. Why are you again installing malt-client when it is already installed?

(2) `Version of python3 on system is 3.9.2-3.`
Buster Raspberry pi has natively python 3.7. If you have python 3.9 then most likely your OS is Bullseye not Buster. Please post output of following commands

`lsb_release -sc `
`cat /etc/os-release `
`apt-cache policy python3 `
`apt-cache policy mlat-client `

**Comment by timtuxworth** [comment]
Thanks for looking at this:

***@***.***:/var/log $ lsb_release -sc 
cat /etc/os-release 
apt-cache policy python3 
apt-cache policy mlat-client
bullseye
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
python3:
  Installed: 3.9.2-3
  Candidate: 3.9.2-3
  Version table:
 *** 3.9.2-3 500
        500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
        100 /var/lib/dpkg/status
mlat-client:
  Installed: 0.2.11
  Candidate: 0.2.11
  Version table:
 *** 0.2.11 100
        100 /var/lib/dpkg/status

**Comment by abcd567a** [comment]
You have Raspberry Pi OS **Bullseye**, but are trying to install mlat-client package for **Buster**, and this caused failure.

Please install mlat-client package for Bullseye:

### First issue following command to determine your OS is 32-bit or 64-bit:
`uname -m  `

### If output of command  `uname -m ` is `armv7l`, use following commands to install 32-bit mlat-client
```
wget https://github.com/abcd567a/mlat-client-package/releases/download/v1/mlat-client_0.2.11_BULLSEYE_armhf.deb  

sudo dpkg -i mlat-client_0.2.11_BULLSEYE_armhf.deb  

```

### If output of command  `uname -m ` is `aarch64`, use following commands to install 64-bit mlat-client
```
wget https://github.com/abcd567a/mlat-client-package/releases/download/v1/mlat-client_0.2.11_BULLSEYE_arm64.deb  

sudo dpkg -i mlat-client_0.2.11_BULLSEYE_arm64.deb  

```

**Comment by timtuxworth** [comment]
Thanks that worked mlat-client is now running

So I have another question. I’m trying to get data from the dump1090 server into Mission Planner so I can feed it to my flight controller.

I have Mission Planner running on my Mac and gave it the IP address of the raspberry Pi and port 30004 to connect to for adsb. Mission Planner is not showing any traffic.

I know there are a lot of possible issue here that have nothing to do with the radar box, but want to ask if there is anything else I need to do on the RadarBox side on the raspberry pi to get this to work?

Tim

**Comment by abcd567a** [comment]
Your ladt question do no pertain to mlat-clent, i.e. this repository. However as you have asked, I will try to answer it.
### dump1090 data
1. Dump1090's port 30004 is NOT an output port, it is input listen post for beast format data.
2. Dump1090's output ports are as follows:
(a) Output port for data in **Raw format: 30002**
(b) Output port for data in **BaseStation format: 30003**
(c) Output port for data in **Beast format: 30005**

### mlat-feedback data from Radarbox24
Mlat feedback from Radarbox24 is available **by default** at port **32004**.

### Check outputs
(1) Install netcat
`sudo apt install netcat  `

(2) Run following commands one by one. **Break continous flow of data by pressing Ctrl and C keys together.**

`nc 127.0.0.1 30002 ` (continous data)

`nc 127.0.0.1 30003 ` (continous data)

`nc 127.0.0.1 30005 ` (continous data)

`nc 127.0.0.1 32004 ` (intermittent data, leave running for 15 minutes)

**Comment by timtuxworth** [comment]
Thanks so much for the extra info I really appreciate it. When I run the nc commands you sent. Nothing happens. Each of them just return immediately without displaying anything.

***@***.***:~ $ nc 127.0.0.1 30002
***@***.***:~ $ nc 127.0.0.1 30003
***@***.***:~ $ nc 127.0.0.1 30004
***@***.***:~ $ nc 127.0.0.1 30005
***@***.***:~ $ 

Tim

**Comment by abcd567a** [comment]
Apparently dump1090-fa is not working.

Please raise your problem in Flightaware forum or Radarbox24 forum, as it is irrelevant to mlat-clant, an i cannot keep on answering your queries here.
