### ISSUE TITLE
mlat doesn't work with Raspberry bookworm

### ISSUE THREAD

**Issue by KBfly** [abcd567a/mlat-client-package#3]
Hi there,

mlat client is not to install with raspberry pi OS bookworm?
see:
mlat-client depends on python3 (<< 3.10); however:
  Version of python3 on system is 3.11.2-1+b1.
 mlat-client depends on python3.9:any.

is there a fix next time?

Thank's Karsten

**Comment by abcd567a** [comment]
The failure is caused because your OS is Bookworm, and you are installing mlat-client package for Bullseye.
Please install mlat-client package for Bookworm
